# Change these first
owner: l1kw1d # Your GitHub username
repo: webuptime # Your Github repository name

# Add your sites here
sites:
  - name: Zombie Technology
    url: https://zombie.technology
  - name: JProvost - my website
    url: https://jprovo.st
  - name: Panel ZST
    url: https://hq.bunkers.co:2083
  - name: FabConcept3D
    url: https://fabconcept3d.com
  - name: Styll Design
    url: https://styll.design
  - name: MiniCasa
    url: https://minicasa.design
  - name: CemaTools
    url: https://cematools.com
  - name: Groupe Lupien
    url: https://groupelupien.com
  - name: Styll Design
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.zombie.technology
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
