# Change these first
owner: l1kw1d # Your GitHub username
repo: webuptime # Your Github repository name


# Add your sites here
assignees:
  - l1kw1d
sites: 
  - name: JProvost - my website
    url: https://jprovo.st
  - name: FabConcept3D
    url: https://fabconcept3d.com
    icon: https://fabconcept3d.com/favicon.ico
  - name: Styll Design
    url: https://styll.design
  - name: MiniCasa
    url: https://minicasa.design
  - name: CemaTools
    url: https://cematools.com/
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: Metallia  
    url: https://www.metallia.ca/
    icon: https://cdn.shopify.com/s/files/1/0544/9518/3021/files/icone-metallia-couleurs_32x32.jpg?v=1613487174
  - name: JoeVee
    url: https://joevee.ca
    icon: https://raw.githubusercontent.com/l1kw1d/joevee-ws/main/img/favicon-32x32.png
    ########################
  - name: WiFi QR 
    url: https://wifi.pin.plus
    icon: https://wifi.pin.plus/favicon.ico
    
    
status-website:
  theme: dark
  cname: up.zombie.technology
  logoUrl: https://github.com/Zombie-Technology/ZSTMAIN/blob/main/assets/images/logos/logo_red_black.png
  name: JP - Surveillance Web 
  introTitle: Websites status monitoring / Surveillance de votre site web
  introMessage: JProvost Cybersec & IT consultant
  navbar:
    - title: Status | JProvost Cybersec & IT consultant
      href:  https://up.zombie.technology
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: My Website
      href: https://pin.plus/JP
    - title: WIFI QR
      href: https://pin.plus/WIFI
      
 
