# Change these first
owner: l1kw1d # Your GitHub username
repo: webuptime # Your Github repository name


# Add your sites here
assignees:
  - l1kw1d
sites:
  - name: Zombie Technology
    url: https://zombie.technology
  - name: Panel ZST
    url: https://hq.bunkers.co:2083
  - name: Relation Manager
    url: https://pampersultra.herokuapp.com/
  - name: JProvost - my website
    url: https://jprovo.st
  - name: WiFi QR 
    url: https://wifi.pin.plus
  - name: FabConcept3D
    url: https://fabconcept3d.com
  - name: Styll Design
    url: https://styll.design
  - name: MiniCasa
    url: https://minicasa.design
  - name: CemaTools
    url: https://cematools.com/
  - name: Metallia  
    url: https://www.metallia.ca/
  - name: JoeVee
    url: https://joevee.ca
    ########################
  - name: Mail Server
    url: https://mc.pin.plus
  - name: Ops! Anti-Phishing
    url: https://breach.website:8338
  - name: Laboratoire Anti-Menace
    url: https://misp.bunkers.co/
  - name: Ops! Prevention
    url: https://watcher.bunkers.co
  
status-website:
  theme: dark
  cname: up.zombie.technology
  logoUrl: https://github.com/Zombie-Technology/ZSTMAIN/blob/main/assets/images/logos/logo_red_black.png
  name: JP - Surveillance Web 
  introTitle: Websites status monitoring / Surveillance de votre site web
  introMessage: JProvost Cybersec & IT consultant
  navbar:
    - title: Status | JProvost Cybersec & IT consultant
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: My Website
      href: https://pin.plus/JP
    - title: WIFI QR
      href: https://pin.plus/WIFI
    - title: Mail Serv
      href: https://mc.pin.plus
 
