# Change these first
owner: l1kw1d # Your GitHub username
repo: webuptime # Your Github repository name

# Add your sites here
assignees:
  - l1kw1d
sites:
  - name: Zombie Technology
    url: https://zombie.technology
  - name: Panel ZST
    url: https://hq.bunkers.co:2083
  - name: Relation Manager
    url: https://zstcrm.herokuapp.com/
  - name: Little Scout
    url: https://pampersultra.herokuapp.com/
  - name: Mail Headers Analyzer
    url: http://mha.bunkers.co
  - name: JProvost - my website
    url: https://jprovo.st
  - name: FabConcept3D
    url: https://fabconcept3d.com
  - name: Styll Design
    url: https://styll.design
  - name: MiniCasa
    url: https://minicasa.design
  - name: CemaTools
    url: https://cematools.com/
  - name: Metallia  
    url: https://www.metallia.ca/
status-website:

  cname: up.zombie.technology
  logoUrl: https://github.com/Zombie-Technology/ZSTMAIN/blob/main/assets/images/logos/logo_red_black.png
  name: ZST Website Uptime
  introTitle: Websites status monitoring / Surveillance de votre site web
  introMessage: JProvost Cybersec & IT consultant
  navbar:
    - title: Status | JProvost Cybersec & IT consultant
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
